### ISSUE TITLE
when i install

### ISSUE THREAD

**Issue by kawayixixing** [GuidoBartoli/sherloq#104]
(.venv) C:\Program Files (x86)\sherloq\sherloq\gui>python sherloq.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\sherloq\sherloq\gui\sherloq.py", line 19, in <module>
    from digest import DigestWidget
  File "C:\Program Files (x86)\sherloq\sherloq\gui\digest.py", line 5, in <module>
    import magic
  File "C:\Program Files (x86)\sherloq\sherloq\.venv\Lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\sherloq\sherloq\.venv\Lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by UHstudent** [comment]
if you use windows / windows powershell/command prompt, "python-magic==0.4.*" from the requirements file is incompatible

to solve this issue:
1. unistall "python-magic==0.4.*" -> pip uninstall python-magic
2. install "python-magic-bin==0.4.14" -> pip install python-magic-bin==0.4.14

note: if python-magic is installed when using windows powershell, sherloq will not run and throw an error because this library is prioritized. Make sure python-magic-bin is installed instead.

Does that work for you?
