### ISSUE TITLE
[Conda] version `Qt_5.15' not found (required by PySide2)

### ISSUE THREAD

**Issue by truatpasteurdotfr** [GuidoBartoli/sherloq#18]
Hi

I am trying to install sherloq through conda +pip  (on CentOS-7) but it seems that the PySide2 is using a newer qt5 version than the conda provided one:
```
(sherloq-pip) [tru@elitebook840g3 gui]$ python3 sherloq.py 
Traceback (most recent call last):
  File "sherloq.py", line 4, in <module>
    from PySide2.QtCore import Qt, QSettings
ImportError: /c7/shared/anaconda3/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /c7/shared/anaconda3/envs/sherloq-pip/lib/python3.8/site-packages/PySide2/QtCore.abi3.so)
```

Procedure used:
- install anaconda3
- conda update anaconda && conda update --all
- conda create --copy -n sherloq-pip python
- conda activate sherloq-pip
- git clone https://github.com/GuidoBartoli/sherloq
- cd sherloq/gui
- python3 -m pip install -r requirements.txt
- python3 sherloq.py

**Comment by GuidoBartoli** [comment]
Hi,
That can be a issue caused by Conda installed on CentOS that is "freezed" on some old packages.

I admit I have very little experience with both environments (I use standard Python environments with `pip` under Ubuntu), maybe @cristi-zz knows better than me (he provided the Conda installation steps for the README).

**Comment by truatpasteurdotfr** [comment]
oh, strange: conda has python-3.7 but while adding the conda env, it pulls python-3.8! I will try to fix version 3.7.
```
[tru@elitebook840g3 ~]$ conda create --copy -n sherloq-pip-py37 python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /c7/shared/anaconda3/envs/sherloq-pip-py37

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.7.7               |       hcff3b4d_5        45.1 MB
    ------------------------------------------------------------
                                           Total:        45.1 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.6.24-0
  certifi            pkgs/main/linux-64::certifi-2020.6.20-py37_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.1.1-py37_1
  python             pkgs/main/linux-64::python-3.7.7-hcff3b4d_5
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-49.2.0-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.32.3-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3

```
whereas:
```
[tru@elitebook840g3 ~]$ conda create --copy -n sherloq-pip python
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /c7/shared/anaconda3/envs/sherloq-pip

  added / updated specs:
    - python


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.6.20          |           py38_0         156 KB
    libffi-3.3                 |       he6710b0_2          50 KB
    pip-20.1.1                 |           py38_1         1.7 MB
    python-3.8.3               |       hcff3b4d_2        49.1 MB
    setuptools-49.2.0          |           py38_0         737 KB
    wheel-0.34.2               |           py38_0          51 KB
    ------------------------------------------------------------
                                           Total:        51.8 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.6.24-0
  certifi            pkgs/main/linux-64::certifi-2020.6.20-py38_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.1.1-py38_1
  python             pkgs/main/linux-64::python-3.8.3-hcff3b4d_2
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-49.2.0-py38_0
  sqlite             pkgs/main/linux-64::sqlite-3.32.3-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3

```

**Comment by truatpasteurdotfr** [comment]
What version of ubuntu are you using? ( I might have missed the info in the repository).

**Comment by truatpasteurdotfr** [comment]
for both pip install (py37 and py38) I have:
```
ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.1 which is incompatible.
```

**Comment by truatpasteurdotfr** [comment]
bummer, both py37/py38 are having the same issue:
```
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ python3 sherloq.py 
Traceback (most recent call last):
  File "sherloq.py", line 4, in <module>
    from PySide2.QtCore import Qt, QSettings
ImportError: /c7/shared/anaconda3/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/PySide2/QtCore.abi3.so)
```
```
(sherloq-pip) [tru@elitebook840g3 gui]$ python sherloq.py 
Traceback (most recent call last):
  File "sherloq.py", line 4, in <module>
    from PySide2.QtCore import Qt, QSettings
ImportError: /c7/shared/anaconda3/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /c7/shared/anaconda3/envs/sherloq-pip/lib/python3.8/site-packages/PySide2/QtCore.abi3.so)
```

**Comment by truatpasteurdotfr** [comment]
I am attaching the `conda env export` outputs
[sherloq-pip.yml.txt](https://github.com/GuidoBartoli/sherloq/files/4932000/sherloq-pip.yml.txt)
[sherloq-pip-py37.yml.txt](https://github.com/GuidoBartoli/sherloq/files/4932001/sherloq-pip-py37.yml.txt)

I have an extra channel, but nothing was used from it, afaik.

**Comment by GuidoBartoli** [comment]
> What version of ubuntu are you using? ( I might have missed the info in the repository).

Ubuntu 20.04 with Python 3.8

> for both pip install (py37 and py38) I have:
> 
> ```
> ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.1 which is incompatible.
> ```

It seems like a [previous issue](https://github.com/GuidoBartoli/sherloq/issues/10) when both `scipy` and `tensorflow` were inside `requirements.txt` and a version clash could occur.
The latest `requirements.txt` from commit 9fbeb713f837a9468d893049bf3ba4d713791b54 is cleaned by `pip-chill` and `scipy` was removed because the correct version is installed by `tensorflow`. Are you using the latest repository version?

**Comment by truatpasteurdotfr** [comment]
I am using:
```
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ git log|head
commit 344ecfc2ff3fe6a593a2f4520771b9a50b4ca04f
Author: Guido Bartoli <guidobartoli80@icloud.com>
Date:   Thu Jul 16 12:13:50 2020 +0200

    Cleaned up merged code for Copy-Move-Forgery (thanks @AlexRiina)

commit cf8a8b0bb2958b742da9bd0f264e966e8ce844ff
Merge: 947d426 125aa3a
```

I will try with ubuntu and py3.8, thanks for looking into this issue!

**Comment by truatpasteurdotfr** [comment]
CentOS-7 qt5 is 5.9.7 as the qt5 from my anaconda3 installlation.

**Comment by truatpasteurdotfr** [comment]
Bummer: there are no 5.9.7 version of pysides through pip
```
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ pip install pyside2==
ERROR: Could not find a version that satisfies the requirement pyside2== (from versions: 0.0.0a1, 5.11.0, 5.11.1, 5.11.2, 5.12.0, 5.12.1, 5.12.2, 5.12.3, 5.12.4, 5.12.5, 5.12.6, 5.13.0, 5.13.1, 5.13.2, 5.14.0, 5.14.1, 5.14.2, 5.14.2.1, 5.14.2.2, 5.14.2.3, 5.15.0)
ERROR: No matching distribution found for pyside2==
```

I could downgrade to the previous version but not far enough...
```
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ pip install pyside2==5.14.2.3
Collecting pyside2==5.14.2.3
  Downloading PySide2-5.14.2.3-5.14.2-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (166.0 MB)
     |████████████████████████████████| 166.0 MB 39 kB/s 
Collecting shiboken2==5.14.2.3
  Downloading shiboken2-5.14.2.3-5.14.2-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (856 kB)
     |████████████████████████████████| 856 kB 4.3 MB/s 
Installing collected packages: shiboken2, pyside2
  Attempting uninstall: shiboken2
    Found existing installation: shiboken2 5.15.0
    Uninstalling shiboken2-5.15.0:
      Successfully uninstalled shiboken2-5.15.0
  Attempting uninstall: pyside2
    Found existing installation: PySide2 5.15.0
    Uninstalling PySide2-5.15.0:
      Successfully uninstalled PySide2-5.15.0
Successfully installed pyside2-5.14.2.3 shiboken2-5.14.2.3
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ python sherloq.py 
Traceback (most recent call last):
  File "sherloq.py", line 4, in <module>
    from PySide2.QtCore import Qt, QSettings
ImportError: /c7/shared/anaconda3/lib/libQt5Core.so.5: version `Qt_5.14' not found (required by /c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/PySide2/QtCore.abi3.so)
```

**Comment by truatpasteurdotfr** [comment]
```
[tru@elitebook840g3 bin]$ conda -V
conda 4.8.3
[tru@elitebook840g3 bin]$ conda list qt
# packages in environment at /c7/shared/anaconda3:
#
# Name                    Version                   Build  Channel
pyqt                      5.9.2            py37h05f1152_2  
qt                        5.9.7                h5867ecd_1  
qtawesome                 0.7.2                      py_0  
qtconsole                 4.7.5                      py_0  
qtpy                      1.9.0                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
```
game over for conda+qt as `pip install pysides ` requires at least 5.11.0

**Comment by truatpasteurdotfr** [comment]
```
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ pip install pyside2==
ERROR: Could not find a version that satisfies the requirement pyside2== (from versions: 0.0.0a1, 5.11.0, 5.11.1, 5.11.2, 5.12.0, 5.12.1, 5.12.2, 5.12.3, 5.12.4, 5.12.5, 5.12.6, 5.13.0, 5.13.1, 5.13.2, 5.14.0, 5.14.1, 5.14.2, 5.14.2.1, 5.14.2.2, 5.14.2.3, 5.15.0)
ERROR: No matching distribution found for pyside2==
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ pip install pyside2==5.11.0
Collecting pyside2==5.11.0
  Downloading PySide2-5.11.0-5.11.0-cp35.cp36-abi3-manylinux1_x86_64.whl (166.4 MB)
     |████████████████████████████████| 166.4 MB 5.8 MB/s 
Installing collected packages: pyside2
  Attempting uninstall: pyside2
    Found existing installation: PySide2 0.0.0a1
    Uninstalling PySide2-0.0.0a1:
      Successfully uninstalled PySide2-0.0.0a1
Successfully installed pyside2-5.11.0
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ python sherloq.py 
Traceback (most recent call last):
  File "sherloq.py", line 4, in <module>
    from PySide2.QtCore import Qt, QSettings
ImportError: /c7/shared/anaconda3/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/PySide2/QtCore.abi3.so)
```

**Comment by truatpasteurdotfr** [comment]
https://pypi.org/project/PySide2/
PySide2 is the official Python module from the Qt for Python project, which provides access to the complete **Qt 5.12+** framework.

**Comment by cristi-zz** [comment]
Hm, that's weird.

I deleted the env and re-created it. The only difference is that I used python instead of python3 (maybe some wrongly wired symlinks?). I went until I opened the GUI. I didn't click around much, to see if all the functions are on.

It is possible that QT was installed before on my machine and somehow picked up all the right so's? 

I still have tensorflow error. TF is hard to install.

Here are some info:
Ubuntu 16.04
conda 4.8.3 [yeah, I know, but it should NOT have any impact. Also miniconda, not full blown anaconda]
Master, commit 344ecfc2ff3fe6a593a2f4520771b9a50b4ca04f

Attached, the exported environment. Note that pip, somehow, managed to install pyside2==5.15.0.
Try cloning my env and see if things work out. A. one more thing, it might matter. I always use --copy for anaconda (doubt that pip obeys this). Somehow, these heavy duty libraries with a lot of dependencies have the bad habit of changing the "anaconda top level" files. I did not investigate much. The point is that I crashed some deep learning env and all of the sudden ALL of them were crashed. (and I didn't change any OS level libraries, only pip/conda commands). 

```
conda create --copy -n sherloq-pip python
conda activate sherloq-pip
git clone https://github.com/GuidoBartoli/sherloq
cd sherloq/gui 
pip install -r requirements.txt
python sherloq.py 
```
At this point, GUI started and I was able to click around.

[working_env.yml.txt](https://github.com/GuidoBartoli/sherloq/files/4932489/working_env.yml.txt) Remove the .txt, git does not like yml.  ``conda env create -f your_yml_file.yml``  according to the docs.

Hope it helps! 

Disclaimer: I don't use this software at the moment. A twitter acquaintance had issues on Mac and I tried to help. 

p.s. What is worth trying is to google for that PySide error. Maybe there is some OS level library that is missing. QT is heavy on its own, so you never know.

**Comment by truatpasteurdotfr** [comment]
Thanks, meanwhile I have install an ubuntu LTS 20.04 and I could have a working version from conda and from the system python.
Qt is indeed available (after `apt-get install qtwayland5`) at version 5.12:
```
ii  libqt5core5a:amd64 5.12.8+dfsg-0ubuntu1 amd64        Qt 5 core module
```
is providing:
```
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12
```

I will try your setup on c7 asap.

**Comment by truatpasteurdotfr** [comment]
Ok I found it, I had an extral LD_LIBRARY_PATH in the way.
Once that extra value removed, your `pip install` procedure it is also working fine on my c7 machine with python-3.8.x.

The python inside the conda env is now finding the *PySides2 provided libQt5Core.so* instead to the conda or OS version:

```
[tru@elitebook840g3 ~]$ find /c7/shared/anaconda3 -name libQt5Core\* -ls
5668376 4055 -rwxr-xr-x   1 tru      Bis       7056208 Jul 16 23:53 /c7/shared/anaconda3/envs/sherloq-pip-issue18/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Core.so.5
5603037 3676 -rwxr-xr-x   1 tru      Bis       6338288 Jul 16 16:34 /c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/PySide2/Qt/lib/libQt5Core.so.5
5430226 4055 -rwxr-xr-x   1 tru      Bis       7056208 Jul 16 16:05 /c7/shared/anaconda3/envs/sherloq-pip/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Core.so.5
4976546    2 -rw-rw-r--   1 tru      Bis          1082 Jul 16 15:46 /c7/shared/anaconda3/lib/libQt5Core.prl
4976555    1 lrwxrwxrwx   1 tru      Bis            19 Jul 16 15:46 /c7/shared/anaconda3/lib/libQt5Core.so.5.9 -> libQt5Core.so.5.9.7
4976558 2598 -rwxrwxr-x   1 tru      Bis       4270856 Jul 16 15:46 /c7/shared/anaconda3/lib/libQt5Core.so.5.9.7
4976552    1 lrwxrwxrwx   1 tru      Bis            19 Jul 16 15:46 /c7/shared/anaconda3/lib/libQt5Core.so.5 -> libQt5Core.so.5.9.7
4976549    1 lrwxrwxrwx   1 tru      Bis            19 Jul 16 15:46 /c7/shared/anaconda3/lib/libQt5Core.so -> libQt5Core.so.5.9.7
4681568 2598 -rwxrwxr-x   1 tru      Bis       4270856 Dec 12  2018 /c7/shared/anaconda3/pkgs/qt-5.9.7-h5867ecd_1/lib/libQt5Core.so.5.9.7
4822647    1 lrwxrwxrwx   1 tru      Bis            19 Dec 12  2018 /c7/shared/anaconda3/pkgs/qt-5.9.7-h5867ecd_1/lib/libQt5Core.so.5.9 -> libQt5Core.so.5.9.7
4715488    2 -rw-rw-r--   1 tru      Bis          1094 Dec 12  2018 /c7/shared/anaconda3/pkgs/qt-5.9.7-h5867ecd_1/lib/libQt5Core.prl
4704101    1 lrwxrwxrwx   1 tru      Bis            19 Dec 12  2018 /c7/shared/anaconda3/pkgs/qt-5.9.7-h5867ecd_1/lib/libQt5Core.so -> libQt5Core.so.5.9.7
4712656    1 lrwxrwxrwx   1 tru      Bis            19 Dec 12  2018 /c7/shared/anaconda3/pkgs/qt-5.9.7-h5867ecd_1/lib/libQt5Core.so.5 -> libQt5Core.so.5.9.7
```
It is only failing now with python-3.7.7 and TF, but that's another story!
```
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ python3 sherloq.py 
Traceback (most recent call last):
  File "sherloq.py", line 41, in <module>
    from splicing import SplicingWidget
  File "/home/tru/zfs/git/github.com/GuidoBartoli/sherloq/gui/splicing.py", line 14, in <module>
    from noiseprint.noiseprint import genNoiseprint
  File "/home/tru/zfs/git/github.com/GuidoBartoli/sherloq/gui/noiseprint/noiseprint.py", line 16, in <module>
    import tensorflow.compat.v1 as tf
  File "/c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 74, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "/c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/tensorflow/python/ops/standard_ops.py", line 27, in <module>
    from tensorflow.python.training.experimental import loss_scaling_gradient_tape
  File "/c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/tensorflow/python/training/experimental/loss_scaling_gradient_tape.py", line 21, in <module>
    from tensorflow.python.distribute import distribution_strategy_context
  File "/c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/tensorflow/python/distribute/__init__.py", line 27, in <module>
    from tensorflow.python.distribute import one_device_strategy
  File "/c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/tensorflow/python/distribute/one_device_strategy.py", line 235, in <module>
    class OneDeviceStrategyV1(distribute_lib.StrategyV1):
  File "/c7/shared/anaconda3/envs/sherloq-pip-py37/lib/python3.7/site-packages/tensorflow/python/distribute/one_device_strategy.py", line 237, in OneDeviceStrategyV1
    __doc__ = OneDeviceStrategy.__doc__.replace(
AttributeError: 'NoneType' object has no attribute 'replace'
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ type python3
python3 is hashed (/c7/shared/anaconda3/envs/sherloq-pip-py37/bin/python3)
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ type python
python is /c7/shared/anaconda3/envs/sherloq-pip-py37/bin/python
(sherloq-pip-py37) [tru@elitebook840g3 gui]$ python3 -V
Python 3.7.7
```
Summary: operator error.... my bad! Sorry for the waste of time!
