### ISSUE TITLE
FAILED TO RUN THE PROGRAM

### ISSUE THREAD

**Issue by fayezslim** [GuidoBartoli/sherloq#26]
(sq) ┌──(kali㉿kali)-[~/Desktop/sherloq/gui]
└─$ python sherloq.py                                                        
Traceback (most recent call last):
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.9/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/sherloq/gui/sherloq.py", line 34, in <module>
    from splicing import SplicingWidget
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/kali/Desktop/sherloq/gui/splicing.py", line 12, in <module>
    from noiseprint.noiseprint import genNoiseprint
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/kali/Desktop/sherloq/gui/noiseprint/noiseprint.py", line 16, in <module>
    import tensorflow.compat.v1 as tf
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.9/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/kali/.virtualenvs/sq/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: invalid ELF header

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by GuidoBartoli** [comment]
Are you sure you installed the correct tensorflow for your platform?

https://stackoverflow.com/questions/38579190/invalid-elf-header-tensorflow

**Comment by fayezslim** [comment]
──(kali㉿kali)-[~]
└─$ pip show tensorflow




Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/kali/.local/lib/python3.9/site-packages
Requires: wheel, grpcio, astor, absl-py, six, termcolor, gast, numpy, protobuf, tensorboard
Required-by:

**Comment by GuidoBartoli** [comment]
Can you show the output of the command `uname -a` launched on the terminal?

**Comment by fayezslim** [comment]
┌──(kali㉿kali)-[~]
└─$ uname -a
Linux kali 5.10.0-kali2-amd64 #1 SMP Debian 5.10.9-1kali1 (2021-01-22) x86_64 GNU/Linux

**Comment by GuidoBartoli** [comment]
Mmmh actually I've only tested Sherloq on Linux Mint (based on Ubuntu). Kali is based on Debian, which in turn is the base of Ubuntu, but maybe there is some compatibility problem with Tensorflow on that platform, I don't know how to help you, sorry...

PS: you have a very nice shell prompt! :wink:

**Comment by fayezslim** [comment]
ohhh i know now why it have run on my linux mint and not on linux and thx
bro your the best

**Comment by GuidoBartoli** [comment]
Thanks man! :smile:
