### ISSUE TITLE
ImportError('failed to find libmagic.  Check your installation') on windows 

### ISSUE THREAD

**Issue by wfrey-bc** [GuidoBartoli/sherloq#46]
after following the installation procedure for windows (using Python 3.9.2) 

(sq) D:\Download\sherloq-master\sherloq-master\gui>pip install -r requirements_win.txt
Collecting tensorflow
  Downloading tensorflow-2.6.0-cp39-cp39-win_amd64.whl (423.3 MB)
     |████████████████████████████████| 423.3 MB 48 kB/s
Collecting astor
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting concurrent-iterator
  Downloading concurrent_iterator-0.2.6-py2.py3-none-any.whl (7.5 kB)
Collecting keras-applications
  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 1.6 MB/s
Collecting lxml
  Downloading lxml-4.6.3-cp39-cp39-win_amd64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 439 kB/s
Collecting opencv-contrib-python-headless
  Downloading opencv_contrib_python_headless-4.5.3.56-cp39-cp39-win_amd64.whl (41.7 MB)
     |████████████████████████████████| 41.7 MB 1.7 MB/s
Collecting pandas
  Downloading pandas-1.3.3-cp39-cp39-win_amd64.whl (10.2 MB)
     |████████████████████████████████| 10.2 MB 1.1 MB/s
Collecting pyside2
  Downloading PySide2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl (136.3 MB)
     |████████████████████████████████| 136.3 MB 62 kB/s
Collecting python-magic
  Downloading python_magic-0.4.24-py2.py3-none-any.whl (12 kB)
Collecting python-magic-bin
  Downloading python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl (409 kB)
     |████████████████████████████████| 409 kB 1.6 MB/s
Collecting rawpy
  Downloading rawpy-0.16.0-cp39-cp39-win_amd64.whl (643 kB)
     |████████████████████████████████| 643 kB 1.7 MB/s
Collecting scikit-image
  Downloading scikit_image-0.18.3-cp39-cp39-win_amd64.whl (12.2 MB)
     |████████████████████████████████| 12.2 MB 1.6 MB/s
Collecting scikit-learn
  Downloading scikit_learn-0.24.2-cp39-cp39-win_amd64.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 819 kB/s
Collecting sewar
  Downloading sewar-0.4.4.tar.gz (10 kB)
Collecting xgboost==1.1.1
  Downloading xgboost-1.1.1-py3-none-win_amd64.whl (54.4 MB)
     |████████████████████████████████| 54.4 MB 1.6 MB/s
Collecting numpy
  Downloading numpy-1.21.2-cp39-cp39-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 1.7 MB/s
Collecting scipy
  Downloading scipy-1.7.1-cp39-cp39-win_amd64.whl (33.8 MB)
     |████████████████████████████████| 33.8 MB 208 kB/s
Collecting tensorflow-estimator~=2.6
  Downloading tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
     |████████████████████████████████| 462 kB 1.7 MB/s
Collecting protobuf>=3.9.2
  Downloading protobuf-3.18.0-cp39-cp39-win_amd64.whl (912 kB)
     |████████████████████████████████| 912 kB 1.7 MB/s
Collecting numpy
  Downloading numpy-1.19.5-cp39-cp39-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 1.6 MB/s
Collecting wrapt~=1.12.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting keras-preprocessing~=1.1.2
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 462 kB/s
Collecting keras~=2.6
  Downloading keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 1.6 MB/s
Collecting gast==0.4.0
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting tensorboard~=2.6
  Downloading tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 1.6 MB/s
Requirement already satisfied: wheel~=0.35 in c:\users\wfrey\envs\sq\lib\site-packages (from tensorflow->-r requirements_win.txt (line 1)) (0.37.0)
Collecting termcolor~=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting opt-einsum~=3.3.0
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 1.0 MB/s
Collecting six~=1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting flatbuffers~=1.12.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting clang~=5.0
  Downloading clang-5.0.tar.gz (30 kB)
Collecting grpcio<2.0,>=1.37.0
  Downloading grpcio-1.40.0-cp39-cp39-win_amd64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 1.6 MB/s
Collecting typing-extensions~=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting astunparse~=1.6.3
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting google-pasta~=0.2
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 1.1 MB/s
Collecting h5py~=3.1.0
  Downloading h5py-3.1.0-cp39-cp39-win_amd64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 1.3 MB/s
Collecting absl-py~=0.10
  Downloading absl_py-0.13.0-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 1.3 MB/s
Collecting decorator
  Downloading decorator-5.1.0-py3-none-any.whl (9.1 kB)
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 1.7 MB/s
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 3.3 MB/s
Collecting shiboken2==5.15.2
  Downloading shiboken2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 1.6 MB/s
Collecting networkx>=2.0
  Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 1.6 MB/s
Collecting tifffile>=2019.7.26
  Downloading tifffile-2021.8.30-py3-none-any.whl (171 kB)
     |████████████████████████████████| 171 kB 1.6 MB/s
Collecting imageio>=2.3.0
  Downloading imageio-2.9.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 6.8 MB/s
Collecting PyWavelets>=1.1.1
  Downloading PyWavelets-1.1.1-cp39-cp39-win_amd64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 1.7 MB/s
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0
  Downloading Pillow-8.3.2-cp39-cp39-win_amd64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 1.6 MB/s
Collecting matplotlib!=3.0.0,>=2.0.0
  Downloading matplotlib-3.4.3-cp39-cp39-win_amd64.whl (7.1 MB)
     |████████████████████████████████| 7.1 MB 1.7 MB/s
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.2.0-py3-none-any.whl (12 kB)
Collecting joblib>=0.11
  Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
     |████████████████████████████████| 303 kB 1.6 MB/s
Collecting pyparsing>=2.2.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 1.3 MB/s
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.2-cp39-cp39-win_amd64.whl (52 kB)
     |████████████████████████████████| 52 kB 331 kB/s
Requirement already satisfied: setuptools>=41.0.0 in c:\users\wfrey\envs\sq\lib\site-packages (from tensorboard~=2.6->tensorflow->-r requirements_win.txt (line 1)) (58.0.4)
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 1.7 MB/s
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 1.4 MB/s
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting requests<3,>=2.21.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 2.3 MB/s
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
     |████████████████████████████████| 781 kB 2.2 MB/s
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
     |████████████████████████████████| 152 kB 1.6 MB/s
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 1.6 MB/s
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 1.7 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     |████████████████████████████████| 145 kB 1.6 MB/s
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 1.2 MB/s
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.5-py3-none-any.whl (37 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 1.7 MB/s
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
     |████████████████████████████████| 146 kB 1.7 MB/s
Building wheels for collected packages: sewar, clang, termcolor, wrapt
  Building wheel for sewar (setup.py) ... done
  Created wheel for sewar: filename=sewar-0.4.4-py3-none-any.whl size=10390 sha256=2b59b8530d8795c03334c4bb8f0c7d332fc23b46b6b902247f91606bbe8e092d
  Stored in directory: c:\users\wfrey\appdata\local\pip\cache\wheels\49\a0\32\0abb7141de45c9d76e08efaffa755a9939c093251231b90259
  Building wheel for clang (setup.py) ... done
  Created wheel for clang: filename=clang-5.0-py3-none-any.whl size=30692 sha256=584e0cb609ba76317a578516602b5708654ec580706132a6b3c1cbd3b9f9acab
  Stored in directory: c:\users\wfrey\appdata\local\pip\cache\wheels\3a\ce\7a\27094f689461801c934296d07078773603663dfcaca63bb064
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4847 sha256=6d70dd14df453f620491bccfcbf32eac23b51572c76075df5f17521c328ddee8
  Stored in directory: c:\users\wfrey\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-py3-none-any.whl size=19572 sha256=736cebd57ab8aaa0ef5d7039c8ae8a0f598c88554bf6f88c4d0dd59b5eccb9ac
  Stored in directory: c:\users\wfrey\appdata\local\pip\cache\wheels\98\23\68\efe259aaca055e93b08e74fbe512819c69a2155c11ba3c0f10
Successfully built sewar clang termcolor wrapt
Installing collected packages: urllib3, pyasn1, idna, charset-normalizer, certifi, six, rsa, requests, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, werkzeug, tensorboard-plugin-wit, tensorboard-data-server, python-dateutil, pyparsing, protobuf, pillow, numpy, markdown, kiwisolver, grpcio, google-auth-oauthlib, cycler, absl-py, wrapt, typing-extensions, tifffile, threadpoolctl, termcolor, tensorflow-estimator, tensorboard, shiboken2, scipy, PyWavelets, pytz, opt-einsum, networkx, matplotlib, keras-preprocessing, keras, joblib, imageio, h5py, google-pasta, gast, flatbuffers, decorator, clang, astunparse, xgboost, tensorflow, sewar, scikit-learn, scikit-image, rawpy, python-magic-bin, python-magic, pyside2, pandas, opencv-contrib-python-headless, lxml, keras-applications, concurrent-iterator, astor
Successfully installed PyWavelets-1.1.1 absl-py-0.13.0 astor-0.8.1 astunparse-1.6.3 cachetools-4.2.2 certifi-2021.5.30 charset-normalizer-2.0.5 clang-5.0 concurrent-iterator-0.2.6 cycler-0.10.0 decorator-5.1.0 flatbuffers-1.12 gast-0.4.0 google-auth-1.35.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.40.0 h5py-3.1.0 idna-3.2 imageio-2.9.0 joblib-1.0.1 keras-2.6.0 keras-applications-1.0.8 keras-preprocessing-1.1.2 kiwisolver-1.3.2 lxml-4.6.3 markdown-3.3.4 matplotlib-3.4.3 networkx-2.6.3 numpy-1.19.5 oauthlib-3.1.1 opencv-contrib-python-headless-4.5.3.56 opt-einsum-3.3.0 pandas-1.3.3 pillow-8.3.2 protobuf-3.18.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-2.4.7 pyside2-5.15.2 python-dateutil-2.8.2 python-magic-0.4.24 python-magic-bin-0.4.14 pytz-2021.1 rawpy-0.16.0 requests-2.26.0 requests-oauthlib-1.3.0 rsa-4.7.2 scikit-image-0.18.3 scikit-learn-0.24.2 scipy-1.7.1 sewar-0.4.4 shiboken2-5.15.2 six-1.15.0 tensorboard-2.6.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.6.0 tensorflow-estimator-2.6.0 termcolor-1.1.0 threadpoolctl-2.2.0 tifffile-2021.8.30 typing-extensions-3.7.4.3 urllib3-1.26.6 werkzeug-2.0.1 wrapt-1.12.1 xgboost-1.1.1

**I get the following error:** 

(sq) D:\Download\sherloq-master\sherloq-master\gui>python sherloq.py
Traceback (most recent call last):
  File "D:\Download\sherloq-master\sherloq-master\gui\sherloq.py", line 12, in <module>
    from digest import DigestWidget
  File "C:\Users\wfrey\Envs\sq\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\Download\sherloq-master\sherloq-master\gui\digest.py", line 5, in <module>
    import magic
  File "C:\Users\wfrey\Envs\sq\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\wfrey\Envs\sq\lib\site-packages\magic\__init__.py", line 208, in <module>
    libmagic = loader.load_lib()
  File "C:\Users\wfrey\Envs\sq\lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
**ImportError: failed to find libmagic.  Check your installation**

(sq) D:\Download\sherloq-master\sherloq-master\gui>

**Comment by GuidoBartoli** [comment]
Does this work for you? (run it from prompt inside **sq** virtual environment)
```
pip uninstall python-magic
pip install python-magic-bin==0.4.14
```

**Comment by wfrey-bc** [comment]
yes, that worked. 

> (sq) D:\Download\sherloq-master\sherloq-master\gui>pip uninstall python-magic
> Found existing installation: python-magic 0.4.24
> Uninstalling python-magic-0.4.24:
>   Would remove:
>     c:\users\wfrey\envs\sq\lib\site-packages\magic\*
>     c:\users\wfrey\envs\sq\lib\site-packages\python_magic-0.4.24.dist-info\*
>   Would not remove (might be manually added):
>     c:\users\wfrey\envs\sq\lib\site-packages\magic\libmagic\libmagic.dll
>     c:\users\wfrey\envs\sq\lib\site-packages\magic\libmagic\magic.mgc
>     c:\users\wfrey\envs\sq\lib\site-packages\magic\magic.py
> Proceed (Y/n)? y
>   Successfully uninstalled python-magic-0.4.24
> 
> (sq) D:\Download\sherloq-master\sherloq-master\gui>pip install python-magic-bin==0.4.14
> Requirement already satisfied: python-magic-bin==0.4.14 in c:\users\wfrey\envs\sq\lib\site-packages (0.4.14)

sherloq is now starting and the GUI appears. 

However trying to load a .JPG image, I get an error "unable to load image!" - without any further details.

**Comment by LorenzNickel** [comment]
I had a similar (probably even the same) issue some weeks ago and I think I was able to mostly fix it (but sadly I'm no longer sure what exactly I installed and uninstalled). Here's my output from `pip freeze`:
```
absl-py==0.13.0
astor==0.8.1
astunparse==1.6.3
cachetools==4.2.2
certifi==2021.5.30
charset-normalizer==2.0.4
clang==5.0
concurrent-iterator==0.2.6
cycler==0.10.0
decorator==5.0.9
flatbuffers==1.12
gast==0.4.0
google-auth==1.34.0
google-auth-oauthlib==0.4.5
google-pasta==0.2.0
grpcio==1.39.0
h5py==3.1.0
idna==3.2
imageio==2.9.0
joblib==1.0.1
keras==2.6.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
libmagic==1.0
lxml==4.6.3
Markdown==3.3.4
matplotlib==3.4.3
networkx==2.6.2
numpy==1.19.5
oauthlib==3.1.1
opencv-contrib-python-headless==4.5.3.56
opt-einsum==3.3.0
pandas==1.3.1
Pillow==8.3.1
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
PySide2==5.15.2
python-dateutil==2.8.2
python-magic-bin==0.4.14
pytz==2021.1
PyWavelets==1.1.1
rawpy==0.16.0
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-image==0.18.2
scikit-learn==0.24.2
scipy==1.7.1
sewar==0.4.4
shiboken2==5.15.2
six==1.15.0
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.6.0
tensorflow-estimator==2.6.0
termcolor==1.1.0
threadpoolctl==2.2.0
tifffile==2021.8.8
typing-extensions==3.7.4.3
urllib3==1.26.6
Werkzeug==2.0.1
wrapt==1.12.1
xgboost==1.1.1
```
As I said, using that most stuff works (including opening JPG-images), just one thing that does not work is the "File Digest" feature. It throws the following error:
```
Traceback (most recent call last):
  File "G:\sherloq\gui\sherloq.py", line 327, in open_tool
    tool_widget = DigestWidget(self.filename, self.image)
  File "G:\sherloq\gui\digest.py", line 37, in __init__
    table.append([None, self.tr("MIME type"), magic.from_file(filename, mime=True)])
AttributeError: module 'magic' has no attribute 'from_file'
```
As I said I'm no longer sure what steps exactly I did, just wanted to throw this in because it might still be helpful here :)

**Comment by GuidoBartoli** [comment]
> yes, that worked.

Ok, I will update the `requirements_win.txt` accordingly, thanks.

> However trying to load a .JPG image, I get an error "unable to load image!" - without any further details.

That's strange, I can load JPG files without problems... Can you please send me the image that you can't load?

**Comment by hdrmadness** [comment]
Hello, excellent software, thank you for sharing. I installed on windows and am seeing both the errors: 

ImportError: failed to find libmagic. Check your installation

Which I was able to fix with:

pip uninstall python-magic
pip install python-magic-bin==0.4.14

but the other issue still persists: 
AttributeError: module 'magic' has no attribute 'from_file'


cheers

**Comment by jshtawayHR** [comment]
I have the issue above and can't use your solution because I get this error:

pip3 install python-magic-bin==0.4.14
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none)
ERROR: No matching distribution found for python-magic-bin==0.4.14
