### ISSUE TITLE
I get errors when running

### ISSUE THREAD

**Issue by sniffedpcs** [GuidoBartoli/sherloq#82]
/Users/mquica/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:tensorflow:From /Users/mquica/Library/Python/3.9/lib/python/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/Users/mquica/sherloq/gui/sherloq.py", line 34, in <module>
    from splicing import SplicingWidget
  File "/Users/mquica/sherloq/gui/splicing.py", line 13, in <module>
    from noiseprint.noiseprint_blind import genMappUint8
  File "/Users/mquica/sherloq/gui/noiseprint/noiseprint_blind.py", line 18, in <module>
    from .utility.utilityRead import resizeMapWithPadding
  File "/Users/mquica/sherloq/gui/noiseprint/utility/utilityRead.py", line 13, in <module>
    from PIL.JpegImagePlugin import convert_dict_qtables
ImportError: cannot import name 'convert_dict_qtables' from 'PIL.JpegImagePlugin' (/Users/mquica/Library/Python/3.9/lib/python/site-packages/PIL/JpegImagePlugin.py)

**Comment by sniffedpcs** [comment]
opened now but got errors

Traceback (most recent call last):
  File "/Users/mquica/sherloq/gui/sherloq.py", line 336, in open_tool
    tool_widget = ExifWidget(self.filename)
  File "/Users/mquica/sherloq/gui/exif.py", line 14, in __init__
    with exiftool.ExifTool(exiftool_exe()) as et:
  File "/Users/mquica/sherloq/gui/pyexiftool/exiftool.py", line 194, in __enter__
    self.start()
  File "/Users/mquica/sherloq/gui/pyexiftool/exiftool.py", line 172, in start
    self._process = subprocess.Popen(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'exiftool'

**Comment by GuidoBartoli** [comment]
It seems that `exiftool` executable is not found by the main script. From the error prompts, I assume you are on MacOS: did you previously install ExifTool from the provided `gui/pyexiftool/exiftool/macos/ExifTool-xx.xx.dmg`?
